version: '2'
services:
  db:
    container_name: zavrsni-mysql
    restart: unless-stopped
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'zavrsni'
    ports:
      - "6612:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
  backend:
    container_name: zavrsni-backend
    restart: on-failure
    image: marki2121/zavrsni-backend:1.7
    environment:
      SPRING_APPLICATION_JSON: '{ 
        "spring.datasource.url": "jdbc:mysql://db:3306/zavrsni?useSSL=false"
      }'
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
      - frontend
  frontend:
    container_name: zavrsni-frontend
    restart: on-failure
    image: marki2121/zavrsni-frontend:1.7
    ports:
      - "9000:80"
    depends_on:
      - backend
      - db
    networks:
      - frontend

networks:
  frontend:
  backend:
